/**
 * Utility functions for exporting data to CSV, JSON, and PDF files in detect_fe.
 */

/**
 * Triggers a browser download of a blob/content file.
 */
const downloadFile = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Clean string values for CSV formatting (escape quotes and handle commas/newlines).
 */
const escapeCSVValue = (val) => {
  if (val === null || val === undefined) return '""';
  if (typeof val === 'object') {
    val = JSON.stringify(val);
  } else {
    val = String(val);
  }
  // Replace double quotes with escaped double quotes
  val = val.replace(/"/g, '""');
  return `"${val}"`;
};

/**
 * Export array of data objects to CSV.
 * @param {string} filename - Output filename (e.g. 'login_history.csv')
 * @param {Array<Object>} data - Data rows
 * @param {Array<{key: string, label: string}>} [columns] - Optional specific columns mapping
 */
export const exportToCSV = (filename, data = [], columns = null) => {
  if (!Array.isArray(data) || data.length === 0) {
    console.warn('No data to export to CSV.');
    return false;
  }

  let headers = [];
  let keys = [];

  if (columns && Array.isArray(columns) && columns.length > 0) {
    keys = columns.map(c => c.key);
    headers = columns.map(c => c.label || c.key);
  } else {
    // Collect all unique keys from data objects
    const keySet = new Set();
    data.forEach(item => {
      if (item && typeof item === 'object') {
        Object.keys(item).forEach(k => keySet.add(k));
      }
    });
    keys = Array.from(keySet);
    headers = keys;
  }

  const csvRows = [];
  // Header row
  csvRows.push(headers.map(h => escapeCSVValue(h)).join(','));

  // Data rows
  data.forEach(row => {
    const values = keys.map(k => escapeCSVValue(row?.[k]));
    csvRows.push(values.join(','));
  });

  const csvContent = csvRows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  
  const finalFilename = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  downloadFile(blob, finalFilename);
  return true;
};

/**
 * Export object or array to JSON.
 * @param {string} filename - Output filename (e.g. 'alerts.json')
 * @param {any} data - Data to stringify
 */
export const exportToJSON = (filename, data = []) => {
  if (!data) {
    console.warn('No data to export to JSON.');
    return false;
  }

  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8;' });

  const finalFilename = filename.endsWith('.json') ? filename : `${filename}.json`;
  downloadFile(blob, finalFilename);
  return true;
};

/**
 * Export array of data objects to PDF using jsPDF + jsPDF-AutoTable.
 * @param {string} filename - Output filename (e.g. 'report.pdf')
 * @param {Array<Object>} data - Data rows
 * @param {Array<{key: string, label: string}>} [columns] - Optional column mapping
 * @param {Object} [meta] - Optional metadata: { title, subtitle, reportedBy, dateRange }
 */
export const exportToPDF = async (filename, data = [], columns = null, meta = {}) => {
  if (!Array.isArray(data) || data.length === 0) {
    console.warn('No data to export to PDF.');
    return false;
  }

  try {
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();

    // ── Header banner ────────────────────────────────────────────────
    doc.setFillColor(10, 15, 30);
    doc.rect(0, 0, pageWidth, 32, 'F');

    doc.setTextColor(56, 189, 248); // cyan
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(meta.title || 'Security Report', 14, 13);

    doc.setTextColor(180, 195, 220);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(meta.subtitle || 'Generated by Detect Security Platform', 14, 20);

    // Right-side metadata
    const now = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });
    doc.setTextColor(120, 140, 170);
    doc.setFontSize(7.5);
    doc.text(`Exported: ${now}`, pageWidth - 14, 13, { align: 'right' });
    if (meta.dateRange) doc.text(`Period: ${meta.dateRange}`, pageWidth - 14, 19, { align: 'right' });
    if (meta.reportedBy) doc.text(`Admin: ${meta.reportedBy}`, pageWidth - 14, 25, { align: 'right' });

    // Thin accent line
    doc.setDrawColor(56, 189, 248);
    doc.setLineWidth(0.4);
    doc.line(0, 32, pageWidth, 32);

    // ── Summary strip ─────────────────────────────────────────────────
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 32, pageWidth, 14, 'F');
    doc.setTextColor(200, 215, 235);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Records: ${data.length}`, 14, 41);
    if (meta.username) doc.text(`User: ${meta.username}`, 70, 41);
    if (meta.email) doc.text(`Email: ${meta.email}`, 140, 41);

    // ── Build table head/body ─────────────────────────────────────────
    let headers = [];
    let keys = [];
    if (columns && Array.isArray(columns) && columns.length > 0) {
      keys = columns.map(c => c.key);
      headers = columns.map(c => c.label || c.key);
    } else {
      const keySet = new Set();
      data.forEach(item => { if (item && typeof item === 'object') Object.keys(item).forEach(k => keySet.add(k)); });
      keys = Array.from(keySet);
      headers = keys;
    }

    const tableBody = data.map(row =>
      keys.map(k => {
        const val = row?.[k];
        if (val === null || val === undefined) return '';
        if (typeof val === 'boolean') return val ? 'Yes' : 'No';
        if (typeof val === 'object') return JSON.stringify(val);
        return String(val);
      })
    );

    autoTable(doc, {
      head: [headers],
      body: tableBody,
      startY: 48,
      margin: { left: 14, right: 14 },
      styles: {
        fontSize: 7.5,
        cellPadding: 3,
        textColor: [200, 215, 235],
        lineColor: [30, 45, 70],
        lineWidth: 0.2,
        fillColor: [12, 20, 38],
        overflow: 'linebreak',
        font: 'helvetica',
      },
      headStyles: {
        fillColor: [20, 35, 65],
        textColor: [56, 189, 248],
        fontStyle: 'bold',
        fontSize: 8,
        halign: 'left',
      },
      alternateRowStyles: {
        fillColor: [16, 26, 46],
      },
      rowPageBreak: 'auto',
      didDrawPage: (hookData) => {
        // Footer on each page
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(7);
        doc.setTextColor(80, 100, 130);
        doc.setFont('helvetica', 'normal');
        doc.text(
          `Page ${hookData.pageNumber} of ${pageCount}  •  Detect Security Platform`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 6,
          { align: 'center' }
        );
      },
    });

    const finalFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
    doc.save(finalFilename);
    return true;
  } catch (err) {
    console.error('PDF export failed:', err);
    return false;
  }
};

